version: '3.9'
services:
  mysql:
    image: "mysql:latest"
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tontinette
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      REDIS_HOST: localhost
      REDIS_PASSWORD: root

  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - 8001:8001

